set global event_scheduler =1;

CREATE EVENT E_testEvent_2 
	ON SCHEDULE EVERY 1 MONTH STARTS DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL DAY(CURDATE())-1 DAY), INTERVAL 1 MONTH),INTERVAL 1 HOUR)
	ON COMPLETION PRESERVE ENABLE
	DO	CALL DEL_SEQ();


