set global event_scheduler =1;

CREATE EVENT E_BYYEAR_EVENT
	ON SCHEDULE EVERY 1 YEAR STARTS DATE_ADD(DATE(CONCAT(YEAR(CURDATE()) + 1,'-',1,'-',1)),INTERVAL 4 HOUR)
	ON COMPLETION PRESERVE ENABLE
	DO	CALL DEL_SEQ();


