delimiter $$

CREATE TABLE `project_fy` (
  `idproject_fy` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_code` varchar(20) DEFAULT NULL COMMENT 'ç¼–å·',
  `seller_name` varchar(20) DEFAULT NULL COMMENT 'å–æ–¹',
  `buyer_name` varchar(20) DEFAULT NULL COMMENT 'ä¹°æ–¹',
  `house_number` varchar(45) DEFAULT NULL COMMENT 'äº§æƒè¯å·',
  `house_XY` varchar(200) DEFAULT NULL COMMENT 'æˆ¿å±‹åè½',
  `house_layers` tinyint(3) unsigned DEFAULT NULL COMMENT 'æ€»å±‚æ•°',
  `house_at_layer` tinyint(3) unsigned DEFAULT NULL COMMENT 'æ‰€åœ¨å±‚æ•°',
  `house_area` float unsigned DEFAULT NULL COMMENT 'å»ºç­‘é¢ç§¯',
  `house_construction` tinyint(3) unsigned DEFAULT NULL COMMENT 'ç»“æž„\\\\n0-é’¢æ··\\\\n1-ç –æ··',
  `house_date` date DEFAULT NULL COMMENT 'å»ºæˆå¹´ä»£',
  `house_decoration` tinyint(3) unsigned DEFAULT NULL COMMENT 'è£…ä¿®\\\\n0-ç²¾è£…\\\\n1-ç®€è£…',
  `house_support` varchar(128) DEFAULT NULL COMMENT 'é…å¥—è®¾æ–½',
  `house_use` varchar(45) DEFAULT NULL COMMENT 'çŽ°ç”¨é€”',
  `house_final_total` int(11) unsigned DEFAULT NULL COMMENT 'æˆäº¤æ€»ä»·',
  `house_evaluate_total` int(11) unsigned DEFAULT NULL COMMENT 'è¯„ä¼°æ€»ä»·',
  `house_final_single` int(11) unsigned DEFAULT NULL COMMENT 'æˆäº¤å¹³ç±³ä»·æ ¼',
  `house_evaluate_single` int(11) unsigned DEFAULT NULL COMMENT 'è¯„ä¼°å¹³ç±³ä»·æ ¼',
  `project_date` date DEFAULT NULL COMMENT 'é¡¹ç›®æ—¶é—´',
  `sell_date` date DEFAULT NULL COMMENT 'æˆäº¤æ—¥æœŸ',
  `project_comment` varchar(400) DEFAULT NULL COMMENT 'æŠ¥å‘Šè´¨é‡ï¼Œæ„è§æµè½¬',
  `processInstanceID` varchar(255) DEFAULT NULL COMMENT 'æµç¨‹å®žä¾‹IDï¼Œ',
  `wuye_name` varchar(45) DEFAULT NULL COMMENT 'ç‰©ä¸šåç§°',
  `wuye_extent` tinyint(3) unsigned DEFAULT NULL COMMENT 'ç‰©ä¸šè§„æ¨¡ï¼Œ1ï¼Œå°ï¼Œ2ï¼Œä¸­ï¼Œ3ï¼Œå¤§',
  `house_holds` tinyint(3) unsigned DEFAULT NULL COMMENT 'æ¥¼å±‚æˆ·æ•°',
  `house_using` tinyint(3) unsigned DEFAULT NULL COMMENT 'è§„åˆ’ç”¨é€”ï¼Œ1ï¼Œä½å®…ï¼Œ2ï¼Œå•†ä¸šï¼Œ3ï¼Œå·¥ä¸š',
  `house_style` tinyint(3) unsigned DEFAULT NULL COMMENT 'æˆ¿å±‹æ ·å¼ 1ã€å•å…ƒæ¥¼ 2ã€å…¸å¼æ¥¼',
  `house_face` tinyint(3) unsigned DEFAULT NULL COMMENT 'æˆ¿å±‹æœå‘ ,1ã€ä¸œã€2ã€å—ã€3ã€è¥¿ã€4ã€åŒ—ã€5ã€ä¸œå—ã€6ã€ä¸œåŒ—ï¼Œ7ã€è¥¿å—ï¼Œ8ã€è¥¿åŒ—',
  `house_property` tinyint(3) unsigned DEFAULT NULL COMMENT 'æˆ¿å±‹æ€§è´¨ï¼Œ1ã€å•†å“æˆ¿ï¼›2ã€ç»é€‚æˆ¿ï¼›3ã€æˆ¿æ”¹æˆ¿ï¼›4ã€å®‰å±…å·¥ç¨‹ï¼›',
  `house_land_property` tinyint(3) unsigned DEFAULT NULL COMMENT 'åœŸåœ°æ€§è´¨ï¼Œ1ã€å›½æœ‰è½¬è®©ï¼›2ã€å›½æœ‰åˆ’æ‹¨ï¼›3ã€é›†ä½“æ‰€æœ‰',
  `sell_mode` tinyint(3) unsigned DEFAULT NULL COMMENT 'æˆäº¤æ–¹å¼ï¼Œ1ã€æ­£å¸¸ï¼›2ã€éžæ­£å¸¸ï¼›',
  `tax_mode` tinyint(3) unsigned DEFAULT NULL COMMENT 'ç¨Žè´¹è´Ÿæ‹…æ–¹å¼ï¼Œ1ã€å„è‡ªï¼›2ã€ä¹°æ–¹ï¼›3ã€å–æ–¹ï¼›',
  `house_road` varchar(400) DEFAULT NULL COMMENT 'å°åŒºé“è·¯æƒ…å†µï¼Œ',
  `house_environment` varchar(400) DEFAULT NULL COMMENT 'å°åŒºçŽ¯å¢ƒæè¿°',
  `kancha_currentstatus` varchar(2048) DEFAULT NULL COMMENT 'çŽ°åœºå‹˜æŸ¥ï¼Œæˆ¿å±‹çŽ°çŠ¶ã€‚',
  `kancha_marketarea` varchar(2048) DEFAULT NULL COMMENT 'å¸‚åœºåŒºåŸŸåˆ†æž',
  `yuping_bianxian` varchar(2048) DEFAULT NULL COMMENT 'æˆ¿äº§å˜çŽ°èƒ½åŠ›åˆ†æž',
  `yuping_diyatishi` varchar(2048) DEFAULT NULL COMMENT 'æˆ¿åœ°äº§æŠµæŠ¼ä¼°ä»·æŠ¥å‘Šä½¿ç”¨æç¤º',
  `project_source` varchar(45) DEFAULT NULL COMMENT 'ä¸šåŠ¡æ¥æº',
  `wuye_at` varchar(128) DEFAULT NULL COMMENT 'ç‰©ä¸šæ‰€åœ¨å°åŒº',
  `house_newnumber` varchar(45) DEFAULT NULL COMMENT 'æ–°è¯å·',
  `similarhouse_total` int(11) unsigned DEFAULT NULL COMMENT 'ä¸Žå¯¹è±¡å„æ–¹é¢ç±»ä¼¼æˆ¿å±‹æˆäº¤ä»·ï¼Œæ€»ä»·',
  `similarhouse_single` int(11) unsigned DEFAULT NULL COMMENT 'ä¸Žå¯¹è±¡å„æ–¹é¢ç±»ä¼¼æˆ¿å±‹æˆäº¤ä»·ï¼Œå•ä»·',
  `house_number_has` tinyint(3) unsigned DEFAULT NULL COMMENT 'èº«ä»½è¯å¤å°ä»¶ï¼Œ1ï¼Œå·²ç»™ï¼Œ2ï¼Œæœªç»™',
  `house_unit_1` tinyint(4) unsigned DEFAULT NULL COMMENT 'æˆ·åž‹----å§å®¤',
  `house_unit_2` tinyint(4) unsigned DEFAULT NULL COMMENT 'æˆ·åž‹-----åŽ…',
  `house_unit_3` tinyint(4) unsigned DEFAULT NULL COMMENT 'æˆ·åž‹----åŽ¨',
  `house_unit_4` tinyint(4) unsigned DEFAULT NULL COMMENT 'æˆ·åž‹------å«',
  `house_unit` tinyint(4) unsigned DEFAULT NULL COMMENT 'æˆ·åž‹---æ ‡å‡†ä»¶ã€å¤å¼ã€åˆ«å¢…ã€åŠžå…¬ã€å•†ä¸šï¼š1.2.3.4.5',
  `house_waiqiang` varchar(45) DEFAULT NULL COMMENT 'å¤–å¢™',
  `house_yangtai` tinyint(4) unsigned DEFAULT NULL COMMENT 'é˜³å°',
  `house_keting_dimian` varchar(45) DEFAULT '0' COMMENT 'å®¢åŽ…åœ°é¢',
  `house_keting_qiangmian` varchar(45) DEFAULT '0' COMMENT 'å®¢åŽ…å¢™é¢',
  `house_keting_dingpeng` varchar(45) DEFAULT '0' COMMENT 'å®¢åŽ…é¡¶æ£š',
  `house_canting_dimian` varchar(45) DEFAULT '0' COMMENT 'é¤åŽ…åœ°é¢',
  `house_canting_qiangmian` varchar(45) DEFAULT '0' COMMENT 'é¤åŽ…å¢™é¢',
  `house_canting_dingpeng` varchar(45) DEFAULT '0' COMMENT 'é¤åŽ…é¡¶æ£š',
  `house_woshi_dimian` varchar(45) DEFAULT '0' COMMENT 'å§å®¤åœ°é¢',
  `house_woshi_qiangmian` varchar(45) DEFAULT '0' COMMENT 'å§å®¤å¢™é¢',
  `house_woshi_dingpeng` varchar(45) DEFAULT '0' COMMENT 'å§å®¤é¡¶æ£š',
  `house_chufang_dimian` varchar(45) DEFAULT '0' COMMENT 'åŽ¨æˆ¿åœ°é¢',
  `house_chufang_qiangmian` varchar(45) DEFAULT '0',
  `house_chufang_dingpeng` varchar(45) DEFAULT '0' COMMENT 'åŽ¨æˆ¿é¡¶æ£š',
  `house_wei_dimain` varchar(45) DEFAULT '0' COMMENT 'å«ç”Ÿé—´åœ°é¢',
  `house_wei_qiangmian` varchar(45) DEFAULT '0' COMMENT 'å«ç”Ÿé—´å¢™é¢',
  `house_wei_dingpeng` varchar(45) DEFAULT '0' COMMENT 'å«ç”Ÿé—´é¡¶æ£š',
  `house_maopi_dimian` varchar(45) DEFAULT '0' COMMENT 'æ¯›å¯æˆ¿åœ°é¢',
  `house_maopi_qiangmian` varchar(45) DEFAULT '0' COMMENT 'æ¯›å¯æˆ¿ï¼Œå¢™é¢',
  `house_window` varchar(128) DEFAULT NULL COMMENT 'é—¨ã€çª—',
  `wuye_manager` tinyint(3) unsigned DEFAULT NULL COMMENT 'ç‰©ä¸šç®¡ç†ï¼šä¸“ä¸šç‰©ä¸šã€å•ä½ç‰©ä¸š',
  `house_will_remove` tinyint(3) unsigned DEFAULT NULL COMMENT 'æ˜¯å¦åˆ—å…¥æ‹†è¿èŒƒå›´',
  `house_lvhua` tinyint(3) unsigned DEFAULT NULL COMMENT 'å°åŒºç»¿åŒ–',
  `pinggu_money` int(10) unsigned DEFAULT '0' COMMENT 'è¯„ä¼°æ”¶è´¹ã€‚',
  `seller_tel` varchar(45) DEFAULT NULL COMMENT 'ä¹°æ–¹è”ç³»æ–¹å¼',
  `buyer_tel` varchar(45) DEFAULT NULL COMMENT 'å–æ–¹è”ç³»æ–¹å¼',
  `house_layer_height` float DEFAULT NULL COMMENT 'å±‚é«˜',
  `house_basement_area` float DEFAULT NULL COMMENT 'åœ°ä¸‹å®¤é¢ç§¯',
  `house_unit_num` tinyint(3) unsigned DEFAULT NULL COMMENT 'ä¸€æ ‹å•å…ƒæ•°',
  `house_maopi_dingpeng` varchar(45) DEFAULT '0' COMMENT 'æ¯›å¯æˆ¿ï¼Œé¡¶æ£š',
  `kancha_date` date DEFAULT NULL COMMENT 'å‹˜æŸ¥æ—¥æœŸ',
  `xiaoqu_extent` tinyint(3) unsigned DEFAULT NULL COMMENT '小区规模，1，小，2，中，3，大',
  PRIMARY KEY (`idproject_fy`),
  UNIQUE KEY `idproject_fy_UNIQUE` (`idproject_fy`)
) ENGINE=InnoDB AUTO_INCREMENT=414 DEFAULT CHARSET=utf8$$

